[reshape(permute(cat(3,retsq_rankcorr_is(:,:,1),retsq_rankcorr_oos(:,:,1)),[3 2 1]),[6,3]),...
    reshape(permute(cat(3,retsq_binary_is(:,:,1),retsq_binary_oos(:,:,1)),[3 2 1]),[6,3]),...
    reshape(permute(cat(3,retsq_absrmse_is(:,:,1),retsq_absrmse_oos(:,:,1)),[3 2 1]),[6,3])]

[reshape(permute(cat(3,retsq_rankcorr_is_avg(:,:,1),retsq_rankcorr_oos_avg(:,:,1)),[3 2 1]),[6,3]),...
    reshape(permute(cat(3,retsq_binary_is_avg(:,:,1),retsq_binary_oos_avg(:,:,1)),[3 2 1]),[6,3]),...
    reshape(permute(cat(3,retsq_absrmse_is_avg(:,:,1),retsq_absrmse_oos_avg(:,:,1)),[3 2 1]),[6,3])]

% 
[reshape(permute(cat(3,retsq_rankcorr_is(:,:,1),retsq_rankcorr_oos(:,:,1)),[3 2 1]),[6,3]),...
    reshape(permute(cat(3,retsq_binary_is(:,:,1),retsq_binary_oos(:,:,1)),[3 2 1]),[6,3]),...
    reshape(permute(cat(3,retsq_absrmse_is(:,:,1),retsq_absrmse_oos(:,:,1)),[3 2 1]),[6,3])]